Repository grytsiuko/Messenger, pull requests merged in 2021-06, with the labels that each got.

#62 Feature/backend/tests
  backend/pom.xml
  backend/src/main/java/messenger/backend/DbInitializer.java
  backend/src/main/java/messenger/backend/auth/AuthService.java
  backend/src/main/java/messenger/backend/chat/exceptions/UserNotMemberOfChatException.java
  backend/src/main/java/messenger/backend/chat/general/GeneralChatService.java
  backend/src/main/java/messenger/backend/chat/group/GroupChatService.java
  backend/src/main/java/messenger/backend/chat/group/exceptions/NotEnoughPermissionLevelException.java
  backend/src/main/java/messenger/backend/chat/group/exceptions/UserNotInChatException.java
  backend/src/main/java/messenger/backend/chat/personal/PersonalChatService.java
  backend/src/main/java/messenger/backend/user/UserController.java
  backend/src/main/java/messenger/backend/user/UserEntity.java
  backend/src/main/java/messenger/backend/user/dto/UserSearchInfoDto.java
  backend/src/test/java/messenger/backend/auth/AuthControllerIT.java
  backend/src/test/java/messenger/backend/chat/general/GeneralChatControllerIT.java
  backend/src/test/java/messenger/backend/chat/group/GroupChatControllerIT.java
  backend/src/test/java/messenger/backend/chat/personal/PersonalChatControllerIT.java
  backend/src/test/java/messenger/backend/message/MessageControllerIT.java
  backend/src/test/java/messenger/backend/user/UserControllerIT.java
  backend/src/test/resources/sql/auth/initAuthTests.sql
  backend/src/test/resources/sql/chat/initGeneralChatTests.sql
  backend/src/test/resources/sql/chat/initGroupChatTests.sql
  backend/src/test/resources/sql/chat/initPersonalChatTests.sql
  backend/src/test/resources/sql/message/initMessageTests.sql
  backend/src/test/resources/sql/user/initUserTests.sql
Labels: theme:build, type:tests

#64 Feature/backend/messages management
  backend/src/main/java/messenger/backend/chat/group/GroupChatService.java
  backend/src/main/java/messenger/backend/chat/personal/PersonalChatService.java
  backend/src/main/java/messenger/backend/message/MessageController.java
  backend/src/main/java/messenger/backend/message/MessageEntity.java
  backend/src/main/java/messenger/backend/message/MessageService.java
  backend/src/main/java/messenger/backend/message/dto/DeleteMessageRequestDto.java
  backend/src/main/java/messenger/backend/message/dto/DeleteMessageSocketDto.java
  backend/src/main/java/messenger/backend/message/dto/MessageResponseDto.java
  backend/src/main/java/messenger/backend/message/dto/UpdateMessageRequestDto.java
  backend/src/main/java/messenger/backend/message/exceptions/MessageNotFoundException.java
  backend/src/main/java/messenger/backend/message/exceptions/UserNotOwnerOfMessage.java
  backend/src/main/java/messenger/backend/sockets/SocketSender.java
  backend/src/main/java/messenger/backend/sockets/SubscribedOn.java
  backend/src/test/java/messenger/backend/message/MessageControllerIT.java
  backend/src/test/resources/sql/message/initMessageTests.sql
Labels: type:features, type:tests

#65 Feature/backend/online status
  backend/src/main/java/messenger/backend/auth/AuthController.java
  backend/src/main/java/messenger/backend/auth/exceptions/NoAccessToken.java
  backend/src/main/java/messenger/backend/auth/jwt/JwtTokenService.java
  backend/src/main/java/messenger/backend/chat/GroupChatEntity.java
  backend/src/main/java/messenger/backend/chat/PrivateChatEntity.java
  backend/src/main/java/messenger/backend/chat/general/GeneralChatRepository.java
  backend/src/main/java/messenger/backend/chat/general/dto/GeneralChatResponseDto.java
  backend/src/main/java/messenger/backend/chat/general/dto/GeneralResponsePersonalExtensionDto.java
  backend/src/main/java/messenger/backend/chat/general/dto/LastSeenResponseDto.java
  backend/src/main/java/messenger/backend/chat/group/GroupChatRepository.java
  backend/src/main/java/messenger/backend/chat/group/GroupChatService.java
  backend/src/main/java/messenger/backend/chat/personal/PersonalChatService.java
  backend/src/main/java/messenger/backend/message/MessageService.java
  backend/src/main/java/messenger/backend/message/dto/DeleteMessageSocketDto.java
  backend/src/main/java/messenger/backend/message/dto/LastMessageResponseDto.java
  backend/src/main/java/messenger/backend/message/dto/MessageResponseDto.java
  backend/src/main/java/messenger/backend/seeds/FakerService.java
  backend/src/main/java/messenger/backend/sockets/SocketSessionEntity.java
  backend/src/main/java/messenger/backend/sockets/SocketSessionRepository.java
  backend/src/main/java/messenger/backend/sockets/SubscribedOn.java
  backend/src/main/java/messenger/backend/sockets/WebSocketConfig.java
  backend/src/main/java/messenger/backend/sockets/WebSocketEventListener.java
  backend/src/main/java/messenger/backend/user/UserController.java
  backend/src/main/java/messenger/backend/user/UserEntity.java
  backend/src/main/java/messenger/backend/user/UserRepository.java
  backend/src/main/java/messenger/backend/user/UserService.java
  backend/src/main/java/messenger/backend/user/dto/ChangePasswordRequestDto.java
  backend/src/main/java/messenger/backend/user/dto/UpdateProfileRequestDto.java
  backend/src/main/java/messenger/backend/userChat/UserChat.java
  backend/src/test/java/messenger/backend/chat/group/GroupChatControllerIT.java
  frontend/src/containers/SocketHome/SocketHome.tsx
Labels: type:features

#67 Feature/backend/user is typing
  backend/src/main/java/messenger/backend/sockets/SubscribedOn.java
  backend/src/main/java/messenger/backend/user/UserController.java
  backend/src/main/java/messenger/backend/user/UserService.java
  backend/src/main/java/messenger/backend/user/dto/ChatIdDto.java
  backend/src/main/java/messenger/backend/user/dto/UserIsTypingDto.java
Labels: type:features

#68 Feature/frontend/messages management
  backend/src/main/java/messenger/backend/message/MessageController.java
  backend/src/main/java/messenger/backend/message/MessageService.java
  backend/src/main/java/messenger/backend/message/dto/DeleteMessageResponseDto.java
  backend/src/main/java/messenger/backend/message/dto/MessageResponseDto.java
  backend/src/main/java/messenger/backend/message/dto/UpdateMessageRequestDto.java
  backend/src/main/java/messenger/backend/message/dto/UpdateMessageResponseDto.java
  backend/src/main/java/messenger/backend/sockets/SocketSender.java
  backend/src/main/java/messenger/backend/sockets/SubscribedOn.java
  backend/src/test/java/messenger/backend/message/MessageControllerIT.java
  frontend/src/api/message/messageModels.ts
  frontend/src/api/message/messageService.ts
  frontend/src/components/ChatSender/ChatSender.module.sass
  frontend/src/components/ChatSender/ChatSender.tsx
  frontend/src/components/Message/Message.tsx
  frontend/src/components/MessageWrapper/MessageWrapper.module.sass
  frontend/src/components/MessageWrapper/MessageWrapper.tsx
  frontend/src/components/MessagesListWrapper/MessagesListWrapper.tsx
  frontend/src/containers/Chat/Chat.tsx
  frontend/src/containers/Chat/models.ts
  frontend/src/containers/Chat/reducers.ts
  frontend/src/containers/Chat/routines.ts
  frontend/src/containers/Chat/sagas.ts
  frontend/src/containers/ChatsList/reducers.ts
  frontend/src/containers/ChatsList/routines.ts
  frontend/src/containers/ChatsList/sagas.ts
  frontend/src/containers/SocketHome/SocketHome.tsx
  frontend/src/containers/SocketHome/routines.ts
  frontend/src/containers/SocketHome/sagas.ts
  frontend/src/helpers/utils.helper.ts
Labels: type:features

#71 Feature/frontend online status
  backend/src/main/java/messenger/backend/sockets/WebSocketEventListener.java
  backend/src/main/java/messenger/backend/user/UserRepository.java
  backend/src/main/java/messenger/backend/user/UserService.java
  frontend/src/api/chat/general/generalChatModels.ts
  frontend/src/api/user/userService.ts
  frontend/src/components/ChatHeader/ChatHeader.tsx
  frontend/src/components/ChatListElement/ChatListElement.module.sass
  frontend/src/components/ChatListElement/ChatListElement.tsx
  frontend/src/components/Message/Message.tsx
  frontend/src/components/MessageWrapper/MessageWrapper.tsx
  frontend/src/components/MessagesListWrapper/MessagesListWrapper.tsx
  frontend/src/components/OnlineMark/OnlineMark.module.sass
  frontend/src/components/OnlineMark/OnlineMark.tsx
  frontend/src/components/UserManager/UserManager.tsx
  frontend/src/containers/Chat/Chat.tsx
  frontend/src/containers/ChatsList/ChatsList.tsx
  frontend/src/containers/GroupChatDetails/GroupChatDetails.tsx
  frontend/src/containers/SocketHome/SocketHome.tsx
  frontend/src/containers/SocketHome/reducers.ts
  frontend/src/containers/SocketHome/routines.ts
  frontend/src/containers/SocketHome/sagas.ts
  frontend/src/reducers/index.ts
Labels: type:features

#73 Fix/socket offline and typing message
  backend/src/main/java/messenger/backend/sockets/WebSocketConfig.java
  backend/src/main/java/messenger/backend/sockets/WebSocketEventListener.java
  frontend/src/components/IsTypingBlock/IsTypingBlock.tsx
Labels: type:fix
