Repository grytsiuko/Messenger, pull requests merged in 2021-04, with the labels that each got.

#23 space commit
  backend/src/main/java/messenger/backend/DbInitializer.java
Labels: type:fix

#24 Fixed labeler
  .github/labeler.yml
  .github/workflows/deploy.yml
  backend/pom.xml
Labels: theme:build, type:fix

#26 Feature/docker
  .github/workflows/deploy.yml
Labels: theme:build, type:fix

#27 Dockerfile created
  backend/.dockerignore
  backend/Dockerfile
Labels: theme:build, type:features, type:fix

#28 Update deploy.yml
  .github/workflows/deploy.yml
Labels: theme:build, type:fix

#29 Update deploy.yml
  .github/workflows/deploy.yml
Labels: theme:build, type:fix

#30 test tr lowercase
  .github/workflows/deploy.yml
Labels: theme:build, type:fix

#31 Update deploy.yml
  .github/workflows/deploy.yml
Labels: theme:build, type:fix

#32 Update deploy.yml
  .github/workflows/deploy.yml
Labels: theme:build

#33 Update deploy.yml
  .github/workflows/deploy.yml
Labels: theme:build, type:fix

#34 Update deploy.yml
  .github/workflows/deploy.yml
Labels: theme:build, type:fix

#35 Feature/docker
  .github/workflows/deploy.yml
  .github/workflows/dockerhub.yml
Labels: theme:build, type:features

#36 Changed dockerhub deploy to release-only
  .github/workflows/dockerhub.yml
Labels: theme:build, type:fix

#37 Actuator add. Change tag.
  .github/workflows/dockerhub.yml
  backend/pom.xml
  backend/src/main/java/messenger/backend/auth/security/SecurityConfig.java
Labels: theme:build, type:features, type:fix

#38 Update dockerhub.yml
  .github/workflows/dockerhub.yml
Labels: theme:build, type:fix

#40 Backend/front link
  backend/src/main/java/messenger/backend/sockets/WebSocketConfig.java
  backend/src/main/resources/application.properties
Labels: theme:build, type:fix

#41 Fix/db seed
  backend/src/main/java/messenger/backend/DbInitializer.java
  backend/src/main/resources/application.properties
Labels: type:fix

#42 Fixed validation
  backend/src/main/java/messenger/backend/auth/dto/AuthRequestDto.java
  backend/src/main/java/messenger/backend/auth/dto/RegisterRequestDto.java
  backend/src/main/java/messenger/backend/chat/general/dto/DeleteChatDto.java
  backend/src/main/java/messenger/backend/chat/group/dto/ChangeGroupChatNameRequestDto.java
  backend/src/main/java/messenger/backend/chat/group/dto/CreateGroupChatRequestDto.java
  backend/src/main/java/messenger/backend/message/dto/SendMessageRequestDto.java
  backend/src/main/java/messenger/backend/user/dto/ChangePasswordRequestDto.java
  backend/src/main/java/messenger/backend/user/dto/UpdateProfileRequestDto.java
  frontend/src/components/CreateGroupChat/CreateGroupChat.tsx
  frontend/src/components/ProfileEdit/ProfileEdit.tsx
  frontend/src/components/RegistrationForm/RegistrationForm.tsx
Labels: type:fix

#43 Fix/read refresh
  backend/src/main/java/messenger/backend/auth/AuthService.java
  backend/src/main/java/messenger/backend/message/MessageEntity.java
  backend/src/main/resources/application.properties
  frontend/src/api/apiClient.ts
  frontend/src/components/Chat/Chat.tsx
  frontend/src/containers/Home/Home.tsx
Labels: type:fix

#44 Feature/docker
  .github/workflows/dockerhub_backend.yml
  .github/workflows/dockerhub_frontend.yml
  backend/pom.xml
  frontend/.dockerignore
  frontend/.gitignore
  frontend/Dockerfile
  frontend/package.json
Labels: theme:build, type:fix

#45 Feature/docker
  .github/workflows/dockerhub_frontend.yml
  backend/src/main/java/messenger/backend/DbInitializer.java
  backend/src/main/java/messenger/backend/sockets/WebSocketConfig.java
Labels: theme:build, type:config

#46 Fix/frontend
  backend/src/main/java/messenger/backend/message/MessageService.java
  backend/src/main/java/messenger/backend/message/dto/MessageSocketResponseDto.java
  backend/src/main/java/messenger/backend/message/dto/SendMessageRequestDto.java
  frontend/src/api/message/messageService.ts
  frontend/src/components/ChatSender/ChatSender.tsx
  frontend/src/components/MessagesListWrapper/MessagesListWrapper.tsx
  frontend/src/containers/Home/Home.tsx
  frontend/src/reducers/chatsList/actions.ts
  frontend/src/reducers/chatsList/reducer.ts
Labels: theme:build, type:fix

#47 Feature/backend/tests Auth
  backend/pom.xml
  backend/src/main/java/messenger/backend/auth/AuthController.java
  backend/src/main/java/messenger/backend/auth/AuthService.java
  backend/src/main/java/messenger/backend/auth/dto/AuthRequestDto.java
  backend/src/main/java/messenger/backend/auth/dto/RefreshTokenDto.java
  backend/src/main/java/messenger/backend/auth/dto/RegisterRequestDto.java
  backend/src/main/java/messenger/backend/chat/ChatSuperclass.java
  backend/src/main/java/messenger/backend/message/MessageEntity.java
  backend/src/main/java/messenger/backend/refreshToken/RefreshTokenEntity.java
  backend/src/main/java/messenger/backend/user/UserEntity.java
  backend/src/main/java/messenger/backend/userChat/UserChat.java
  backend/src/test/java/messenger/backend/TemporarySetTests.java
  backend/src/test/java/messenger/backend/auth/AuthControllerIT.java
  backend/src/test/resources/application.properties
  backend/src/test/resources/sql/clean.sql
  backend/src/test/resources/sql/init.sql
Labels: theme:build, type:tests

#50 Done general chat tests
  backend/src/main/java/messenger/backend/chat/ChatSuperclass.java
  backend/src/main/java/messenger/backend/chat/GroupChatEntity.java
  backend/src/main/java/messenger/backend/message/MessageEntity.java
  backend/src/main/java/messenger/backend/refreshToken/RefreshTokenEntity.java
  backend/src/main/java/messenger/backend/user/UserEntity.java
  backend/src/main/java/messenger/backend/userChat/UserChat.java
  backend/src/test/java/messenger/backend/chat/general/GeneralChatControllerIT.java
  backend/src/test/resources/sql/init.sql
Labels: theme:build, type:tests

#51 Changed workflow to trigger the hook on release
  .github/workflows/dockerhub_backend.yml
  .github/workflows/dockerhub_deploy.yml
  .github/workflows/dockerhub_frontend.yml
  .github/workflows/gitpackages_deploy.yml
Labels: theme:build, type:features

#52 Update build.yml
  .github/workflows/build.yml
Labels: theme:build, type:fix

#57 Feature/grouppictures
  backend/src/main/java/messenger/backend/DbInitializer.java
  backend/src/main/java/messenger/backend/chat/GroupChatEntity.java
  backend/src/main/java/messenger/backend/chat/general/dto/GeneralChatResponseDto.java
  backend/src/main/java/messenger/backend/chat/group/GroupChatService.java
  backend/src/main/java/messenger/backend/chat/group/dto/ChangeGroupChatNameRequestDto.java
  backend/src/main/java/messenger/backend/chat/group/dto/GroupChatResponseDto.java
  backend/src/main/java/messenger/backend/seeds/FakerService.java
  backend/src/main/java/messenger/backend/user/UserEntity.java
  backend/src/main/java/messenger/backend/user/UserService.java
  backend/src/main/java/messenger/backend/user/dto/CurrentUserInfoDto.java
  backend/src/main/java/messenger/backend/user/dto/UpdateProfileRequestDto.java
  backend/src/main/java/messenger/backend/user/dto/UserSearchInfoDto.java
  backend/src/main/java/messenger/backend/user/dto/UserShortDto.java
  backend/src/main/resources/application.properties
  backend/src/test/java/messenger/backend/user/UserControllerIT.java
  frontend/src/api/auth/authModels.ts
  frontend/src/api/chat/general/generalChatModels.ts
  frontend/src/api/chat/group/groupChatModels.ts
  frontend/src/api/chat/group/groupChatService.ts
  frontend/src/api/user/userModels.ts
  frontend/src/components/ChatListElement/ChatListElement.module.sass
  frontend/src/components/ChatListElement/ChatListElement.tsx
  frontend/src/components/GroupChatDetails/GroupChatDetails.module.sass
  frontend/src/components/GroupChatDetails/GroupChatDetails.tsx
  frontend/src/components/ProfileEdit/ProfileEdit.module.sass
  frontend/src/components/ProfileEdit/ProfileEdit.tsx
  frontend/src/components/UserCard/UserCard.module.sass
  frontend/src/components/UserCard/UserCard.tsx
Labels: theme:build, type:features

#58 Feature/leave chat
  backend/src/main/java/messenger/backend/chat/group/GroupChatController.java
  backend/src/main/java/messenger/backend/chat/group/GroupChatService.java
  frontend/src/api/chat/group/groupChatService.ts
  frontend/src/components/GroupChatDetails/GroupChatDetails.tsx
  frontend/src/containers/Home/Home.tsx
Labels: theme:build, type:features

#59 Update ProfileEdit.module.sass
  frontend/src/components/ProfileEdit/ProfileEdit.module.sass
Labels: theme:build, type:fix
